name: Build and Test logstash-input-opensearch plugin
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  Build:
    strategy:
      matrix:
        logstash: [ "7.16.3" ]
        opensearch: [ "1.2.1" ]
        secure: [ false ]
    name: Build and Test logstash-input-opensearch
    runs-on: ubuntu-latest
    env:
      OPENSEARCH_VERSION: ${{ matrix.opensearch }}
      LOGSTASH_VERSION: ${{ matrix.logstash }}
      SECURE_INTEGRATION: ${{ matrix.secure }}
    steps:
      - name: Checkout plugin
        uses: actions/checkout@v1

      - name: Build and pull docker files
        run: |
          ./.ci/docker-setup.sh

      - name: Run integration tests
        run: |
          ./.ci/docker-run.sh
